Use RollingUpdate instead of Rolling
error: Deployment.apps "perl-testing" is invalid: spec.strategy: Unsupported value: apps.DeploymentStrategy{Type:"Rolling", RollingUpdate:(*apps.RollingUpdateDeployment)(nil)}: supported values: "Recreate", "RollingUpdate"

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>